/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MercatoRouteImport } from './routes/mercato'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DefiRouteImport } from './routes/defi'
import { Route as BilanRouteImport } from './routes/bilan'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MercatoRoute = MercatoRouteImport.update({
  id: '/mercato',
  path: '/mercato',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DefiRoute = DefiRouteImport.update({
  id: '/defi',
  path: '/defi',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanRoute = BilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bilan': typeof BilanRoute
  '/defi': typeof DefiRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mercato': typeof MercatoRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/matches/$id': typeof MatchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bilan': typeof BilanRoute
  '/defi': typeof DefiRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mercato': typeof MercatoRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/matches/$id': typeof MatchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bilan': typeof BilanRoute
  '/defi': typeof DefiRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/mercato': typeof MercatoRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/matches/$id': typeof MatchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bilan'
    | '/defi'
    | '/guide'
    | '/home'
    | '/login'
    | '/mercato'
    | '/pricing'
    | '/register'
    | '/settings'
    | '/matches/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bilan'
    | '/defi'
    | '/guide'
    | '/home'
    | '/login'
    | '/mercato'
    | '/pricing'
    | '/register'
    | '/settings'
    | '/matches/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bilan'
    | '/defi'
    | '/guide'
    | '/home'
    | '/login'
    | '/mercato'
    | '/pricing'
    | '/register'
    | '/settings'
    | '/matches/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BilanRoute: typeof BilanRoute
  DefiRoute: typeof DefiRoute
  GuideRoute: typeof GuideRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MercatoRoute: typeof MercatoRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  MatchesIdRoute: typeof MatchesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercato': {
      id: '/mercato'
      path: '/mercato'
      fullPath: '/mercato'
      preLoaderRoute: typeof MercatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defi': {
      id: '/defi'
      path: '/defi'
      fullPath: '/defi'
      preLoaderRoute: typeof DefiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan': {
      id: '/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof BilanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BilanRoute: BilanRoute,
  DefiRoute: DefiRoute,
  GuideRoute: GuideRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MercatoRoute: MercatoRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  MatchesIdRoute: MatchesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
